### ISSUE TITLE
"Restart Komodo" infobar makes left pane very big

### ISSUE THREAD

**Issue by Defman21** [Naatan/TabulaRasa#11]
![screen](http://i.imgur.com/0OqAF49.png)
Should do something with that.

**Comment by Naatan** [comment]
Yup, thats cause I made the main komodo wrapper a hbox with CSS. I need to add a script which instead moves the toolbar to komodo-hbox.

**Comment by Defman21** [comment]
Fixed somewhere in the latest commits :stuck_out_tongue:
