### ISSUE TITLE
vertical tabs broken

### ISSUE THREAD

**Issue by babobski** [Naatan/TabulaRasa#18]
@Naatan was testing the look and feel of my addons in difrent skins, when i saw that the vertical tabs are not showing his tabs.
![snap 2015-10-10 at 13 03 53](https://cloud.githubusercontent.com/assets/3530262/10410848/6abcd378-6f4f-11e5-9419-7843a00b692d.png)

**Comment by hoppfrosch** [comment]
This is a duplicate of #17

**Comment by babobski** [comment]
yes it is
